language: python

python:
    - "3.9"
    - "3.10"
    - "3.11"

env:
    - REQUIREMENTS="Django==3.2.16"
    - REQUIREMENTS="Django==4.1.5"

cache: pip

install:
    - pip install $REQUIREMENTS
    - pip install django-pagination-py3
    - pip install feedparser==6.0.10
    - pip install coverage==7.1.0
    - pip install python-coveralls==2.9.3
    - pip install factory-boy==3.2.1
    - export PYTHONPATH=.

before_script: coverage erase

script: coverage run --source=planet manage.py test --settings=testsettings

after_success: coverage report; coveralls
