name: Create Draft Release

on:
  workflow_dispatch:
  push:
    tags:
    - "v*"

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1
      with:
        draft: true
        allowUpdates: true
        generateReleaseNotes: true
