# Generated by Django 5.2.6 on 2026-03-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="original_content",
            field=models.TextField(blank=True, null=True, verbose_name="Original Content"),
        ),
    ]
